config/routes.rb
Tuntun::Application.routes.draw do
  root to: 'welcome#index'

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy', as: "destroy_user_session"
  end

  resources :pokes, only: [:create] do
    member do
      get "reply"
    end
  end

end

app/models/poke.rb
class Poke
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Paperclip

  field :time, type: Integer, default: 5
  field :message, type: String, default: ""
  field :open, type: Boolean, default: false

  has_mongoid_attached_file :image, styles: {thumb: "100x100>" }

  belongs_to :author, class_name: "User", inverse_of: :poked
  belongs_to :target, class_name: "User", inverse_of: :targeted
end

app/models/user.rb
# -*- coding: utf-8 -*-
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, :trackable

  ## Omniauthable
  field :twitter_id,  type: String
  field :name,        type: String
  field :nick,        type: String
  field :profile,     type: String
  field :icon_url,    type: String
  
  field :access_token,  type: String
  field :access_secret, type: String

  ## Database authenticatable
  # field :email,              :type => String, :default => ""
  # field :encrypted_password, :type => String, :default => ""

  ## Recoverable
  # field :reset_password_token,   :type => String
  # field :reset_password_sent_at, :type => Time

  ## Rememberable
  # field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  ## Token authenticatable
  field :authentication_token, type: String

  has_many :poked, class_name: "Poke", inverse_of: :author
  has_many :targeted, class_name: "Poke", inverse_of: :target

  def friend?(screen_name)
    begin
      friendship = self.client.friendship(self.name, screen_name)[:source]
      return (friendship[:following] && friendship[:followed_by])
    rescue
      return false
    end
  end

  def invite(screen_name)
    begin
      if self.user(screen_name)
        self.client.update("@#{screen_name} つんつん http://tuntun.herokuapp.com/")
      end
    end
  end

  def user(screen_name)
    begin
      self.client.user(screen_name)
    rescue
      false
    end
  end

  def client
    client = Twitter::Client.new(
                                 consumer_key:       Settings.twitter.key ,
                                 consumer_secret:    Settings.twitter.secret,
                                 oauth_token:        self.access_token,
                                 oauth_token_secret: self.access_secret
                                 )
  end
end

app/controllers/api/v1/pokes_controller.rb
class Api::V1::PokesController < ApplicationController
  def index
  end

  def create
  end

  def show
  end

  def destroy
  end

  private
  def poke_params
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController  < Devise::OmniauthCallbacksController

  def twitter
    auth          = request.env["omniauth.auth"]
    twitter_id    = auth["uid"]
    name          = auth["info"]["nickname"]
    nick          = auth["info"]["screen_name"]
    icon_url      = auth["info"]["image"]
    profile       = auth["info"]["description"]
    access_token  = auth["credentials"]["token"]
    access_secret = auth["credentials"]["secret"]

    user = User.find_or_initialize_by(twitter_id: twitter_id)

    user.twitter_id    = twitter_id
    user.name          = name
    user.nick          = nick
    user.icon_url      = icon_url
    user.profile       = profile
    user.access_token  = access_token
    user.access_secret = access_secret
    user.authentication_token = Digest::MD5.new.update(access_secret).to_s

    user.save
    
    #render json: user.to_json
    sign_in_and_redirect user
  end
end

app/controllers/pokes_controller.rb
# -*- coding: utf-8 -*-
class PokesController < ApplicationController
  def create
    begin
      if current_user.friend?(poke_target_param[:target])
        if User.where(name: poke_target_param[:target]).count > 0
          @poke = Poke.new(poke_params)
          @poke.target = User.where(name: poke_target_param[:target]).first
          @poke.author = current_user
          if @poke.save
            redirect_to root_path, flash: { notice: "つんつんしました！"}
          else
            redirect_to root_path, flash: { error: "Document Saving Error"}
          end
        else
          current_user.invite(poke_target_param[:target])
          redirect_to root_path, flash: {notice: "@#{poke_target_param[:target]}を招待しました！"}
        end
      else
        redirect_to root_path, flash: {error: "Not Friend!"}
      end
    rescue
      redirect_to root_path, flash: {error: " We're sorry.but something went wrong."}
    end
  end

  def reply
    begin
      if @poke = Poke.find(params[:id])
        if !@poke.open
          @poke.open = true
          @poke.save
        end
        @reply = Poke.new
        @reply.author = current_user
        @reply.target = @poke.author
        if @reply.save
          redirect_to root_path, flash: { notice: "つんつんしました！"}
        else
          redirect_to root_path, flash: { error: "Document Saving Error"}
        end
      else
        redirect_to root_path, flash: {error: " Not Found."}
      end
    rescue
      redirect_to root_path, flash: {error: " We're sorry.but something went wrong."}
    end
  end

  def show
    begin
      if @poke = Poke.find(params[:id])
        if !@poke.open
          @poke.open = true
          @poke.save
        end
      else
        redirect_to root_path, flash: {error: " Not Found."}
      end
    rescue
      redirect_to root_path, flash: {error: " We're sorry.but something went wrong."}
    end
  end

  def destroy
    begin
      @poke = Poke.find(params[:id])
      @poke.delete
    end
    redirect_to root_path
  end

  private
  def poke_params
    params.require(:poke).permit(:time, :message, :image)
  end

  def poke_target_param
    params.require(:poke).permit(:target)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @users = User.all

    if user_signed_in?
      @poke = Poke.new
      @pokes = current_user.poked + current_user.targeted
      @pokes.sort!{ |a, b|
        b.created_at <=> a.created_at
      }
    end

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/pokes_helper.rb
module PokesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="ja")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    /%meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title つんつん(&beta;)
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"

    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
  %body
    #wrap
      .container
        .page-header        
          %h1
            つんつん(&beta;)
            %span.pull-right
              - if user_signed_in?
                = link_to image_tag(current_user.icon_url, class: "img-circle"), "http://twitter.com/#{current_user.name}"

        - flash.each do |name, msg| 
          - if msg.is_a?(String)
            %div(class="alert alert-#{name == :notice ? "success" : "danger"}")
              %a.close(data-dismiss="alert")
                = raw('&times;')
              = content_tag :div, msg, :id => "flash_#{name}" 
        = yield


    #footer
      .container
        .pull-left
          %p.text-muted.credit
            %a(href="https://www.facebook.com/groups/onct.iitomo/")
              About us
          
        .pull-right
          %p.text-muted.credit
            &copy; いいとも!を見る会 2013

    = javascript_include_tag "application"

app/views/welcome/admin.html.haml
%h1 Welcome#admin
%p Find me in app/views/welcome/admin.html.haml
- @users.each do |user|
  .well
    %p= user.name
    %p= user.access_token
    %p= user.access_secret

app/views/welcome/index.html.haml
.jumbotron
  .container
    %p
      FacebookのPokeが大好きなボク達は驚いた。
    %p
      普段使ってるTwitterにPokeが無いことに。
    - if user_signed_in?
      %small
        = "@#{current_user.name}としてログインしています。"
    %p
      - if user_signed_in?
        .pull-right
          = link_to "ログアウト", destroy_user_session_path, class: "btn btn-danger"
      - else
        = link_to "Twitterでログイン", user_omniauth_authorize_path(:twitter), class: "btn btn-primary btn-lg"


- if user_signed_in?
  .well
    .container
      = form_for(@poke, html:{class: "", role: "form"}) do |f|
        .form-group
          %label.sr-only(for="poke_target")Target User
          .input-group
            %span.input-group-addon @
            = f.text_field :target, class: "form-control", placeholder: "Username"
        .form-group
          %label.sr-only(for="poke_message")Message
          = f.text_area :message,  disabled: "", class: "form-control", placeholder: "Coming soon!"
        %label.sr-only(for="poke") Time
        .row
          .col-xs-3
            .input-group
              = f.number_field :time, disabled: "", class: "form-control"
              %span.input-group-addon sec

        .pull-right
          = f.submit "つんつん", class: "btn btn-primary btn-large"


  .panel.panel-primary
    .panel-heading
      %h3.panel-title つんつん
    %ul.list-group
      - @pokes.each do |poke|
        %li.list-group-item
          - if current_user.id == poke.target.id
            %i.glyphicon.glyphicon-hand-right
            = link_to "@#{poke.author.name}", "http://twitter.com/#{poke.author.name}"
            につんつんされました。
            (#{time_ago_in_words poke.created_at}前)
            .pull-right

              %a(href="#{reply_poke_path(poke.id)}")
                %i.glyphicon.glyphicon-share-alt
                Reply
          - else
            %i.glyphicon.glyphicon-hand-left
            = link_to "@#{poke.target.name}", "http://twitter.com/#{poke.target.name}"
            につんつんしました。
            (#{time_ago_in_words poke.created_at}前)


      